#spring:
#  application:
#    name: movieAPI
#

spring:
  datasource:
    username: root
    password: topik712
    url: jdbc:mysql://localhost:3306/movieAPI
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format-sql: true

